// Worker entry point.
//
// Terminates the WebSocket upgrade, gates it with a lazy per-user access check
// against apps/web (stale-while-revalidate, evaluated ONLY here at the upgrade
// — never per relayed message), bounds raw attempts with ConnRateDO, then
// forwards the upgrade to the room DO. All non-WS requests get a 404.

import { ConnRateDO } from "./conn-rate-do";
import { RoomDO } from "./room-do";

export { ConnRateDO, RoomDO };

// Env is generated by `wrangler types` into worker-configuration.d.ts.

const SUPPORTED_PROTOCOL_VERSIONS = new Set([1]);

// Positive cache TTL. After this a cached user is "stale" — still served from
// last-good, but a background refresh fires (see stale-while-revalidate below).
const POSITIVE_TTL_MS = 60_000;

// /check is given a short edge cacheTtl so bursts of true-misses for the same
// user collapse onto one origin hit.
const CHECK_CACHE_TTL_SECONDS = 30;

// Connection-rate caps. Coarse abuse bounds, NOT per-message rate limiting
// (that lives in the room DO). Consulted once per upgrade. Exported so the
// test suite can drive exactly past the cap.
const CONN_RATE_WINDOW_MS = 60_000;
export const CONN_RATE_LIMIT_PER_IP = 120;
export const CONN_RATE_LIMIT_PER_UG = 30;

// Isolate-global positive cache. There is intentionally NO negative cache:
// a "not allowed" answer is never remembered, so an unsubscribe/resubscribe
// takes effect on the very next true-miss check. Abuse from the resulting
// uncached re-checks is bounded by ConnRateDO.
const positiveCache = new Map<string, { expiresAt: number }>();

// Accept the WS upgrade then immediately close with the given code/reason.
// Used for failures that occur after the upgrade decision but before we hand
// control to the DO — clients always see a WS close instead of a surprise
// HTTP error.
function acceptAndClose(code: number, reason: string): Response {
  const pair = new WebSocketPair();
  const server = pair[1];
  server.accept();
  server.close(code, reason);
  return new Response(null, { status: 101, webSocket: pair[0] });
}

// One /check round-trip. Throws on transport failure (caller decides how to
// degrade); returns the boolean `allowed` on a clean response.
async function fetchAllowed(env: Env, userId: string): Promise<boolean> {
  const res = await fetch(
    `${env.ZIVA_API_BASE}/api/multiplayer/check?u=${encodeURIComponent(userId)}`,
    { cf: { cacheTtl: CHECK_CACHE_TTL_SECONDS } },
  );
  if (!res.ok) {
    throw new Error(`check returned ${res.status}`);
  }
  const body = (await res.json()) as { allowed?: unknown };
  return body.allowed === true;
}

// Decide whether `userId` may connect, applying stale-while-revalidate against
// the isolate-global positive cache. Returns true to allow, false to deny.
//
// - fresh hit                  → allow, no fetch
// - stale (expired) hit        → allow immediately; refresh in the background
// - true miss                  → one blocking /check; cache+allow or deny
//
// Failure modes (loud, never silent):
// - /check throws on a true miss          → deny (fail CLOSED). The caller
//   maps this to close code "check_unavailable".
// - /check throws but a positive entry    → serve last-good AND console.error.
//   exists (even if expired)                Keeps subscribers online through a
//                                            transient apps/web outage.
async function checkAllowed(
  env: Env,
  ctx: ExecutionContext,
  userId: string,
): Promise<{ allowed: boolean; reason: "ok" | "not_allowed" | "check_unavailable" }> {
  const now = Date.now();
  const cached = positiveCache.get(userId);

  if (cached && cached.expiresAt > now) {
    return { allowed: true, reason: "ok" };
  }

  if (cached) {
    // Stale positive entry: serve it now, revalidate out of band. The join
    // never blocks on the refresh.
    ctx.waitUntil(
      (async () => {
        try {
          const allowed = await fetchAllowed(env, userId);
          if (allowed) {
            positiveCache.set(userId, { expiresAt: Date.now() + POSITIVE_TTL_MS });
          } else {
            // Access revoked while cached — drop so the next attempt is a
            // true miss and gets denied.
            positiveCache.delete(userId);
          }
        } catch (err) {
          // Refresh failed; keep last-good so the user isn't kicked on a blip.
          console.error(
            `multiplayer check refresh failed for ${userId}: ${(err as Error).message}`,
          );
        }
      })(),
    );
    return { allowed: true, reason: "ok" };
  }

  // True miss — blocking check.
  try {
    const allowed = await fetchAllowed(env, userId);
    if (allowed) {
      positiveCache.set(userId, { expiresAt: now + POSITIVE_TTL_MS });
      return { allowed: true, reason: "ok" };
    }
    return { allowed: false, reason: "not_allowed" };
  } catch (err) {
    // True miss + transport failure: fail CLOSED. We have no last-good to
    // fall back to and must never let an unverified user in.
    console.error(
      `multiplayer check failed (no cached entry) for ${userId}: ${(err as Error).message}`,
    );
    return { allowed: false, reason: "check_unavailable" };
  }
}

// Parse the room id out of the `/r/<room>` path segment.
function parseRoomId(url: URL): string | null {
  const parts = url.pathname.split("/").filter((p) => p.length > 0);
  if (parts.length >= 2 && parts[0] === "r") {
    return decodeURIComponent(parts[1]);
  }
  return null;
}

// Bound raw connection attempts before any /check fan-out. Keyed per-IP and
// per-(u,g); either window tripping rejects the attempt.
async function withinConnRate(
  env: Env,
  ip: string,
  userId: string,
  gameId: string,
): Promise<boolean> {
  const ipStub = env.CONN_RATE.getByName(`ip:${ip}`);
  const ugStub = env.CONN_RATE.getByName(`ug:${userId}:${gameId}`);
  const [ipOk, ugOk] = await Promise.all([
    ipStub.hit(CONN_RATE_LIMIT_PER_IP, CONN_RATE_WINDOW_MS),
    ugStub.hit(CONN_RATE_LIMIT_PER_UG, CONN_RATE_WINDOW_MS),
  ]);
  return ipOk && ugOk;
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
      return new Response("ziva-multiplayer relay — websocket only", { status: 404 });
    }

    const url = new URL(request.url);
    const versionRaw = url.searchParams.get("v");
    const version = versionRaw === null ? 1 : Number(versionRaw);
    if (!Number.isInteger(version) || !SUPPORTED_PROTOCOL_VERSIONS.has(version)) {
      return acceptAndClose(1008, "unsupported_protocol_version");
    }

    const userId = url.searchParams.get("u");
    const gameId = url.searchParams.get("g");
    const room = parseRoomId(url);
    if (!userId || !gameId || !room) {
      return acceptAndClose(1008, "missing_params");
    }

    // Bound raw attempts FIRST so the no-negative-cache /check below can't be
    // weaponized into unbounded origin fan-out.
    const ip = request.headers.get("CF-Connecting-IP") ?? "unknown";
    if (!(await withinConnRate(env, ip, userId, gameId))) {
      return acceptAndClose(1008, "rate_limited");
    }

    const decision = await checkAllowed(env, ctx, userId);
    if (!decision.allowed) {
      return acceptAndClose(1008, decision.reason);
    }

    // RoomDO is named by room id — same room id always lands on the same DO
    // instance globally.
    const stub = env.ROOM.getByName(room);

    // Forward the upgrade. The DO trusts these headers because only this
    // Worker (same script binding) can set them.
    const upstreamReq = new Request(request.url, request);
    upstreamReq.headers.set("X-Ziva-Sub", userId);
    upstreamReq.headers.set("X-Ziva-Game", gameId);
    upstreamReq.headers.set("X-Ziva-Rid", room);
    upstreamReq.headers.set("X-Ziva-Version", String(version));

    return stub.fetch(upstreamReq);
  },
} satisfies ExportedHandler<Env>;
