// Worker entry point.
//
// Terminates the WebSocket upgrade, gates it with a lazy per-user access check
// against apps/web (stale-while-revalidate, evaluated ONLY here at the upgrade
// — never per relayed message), bounds raw attempts with ConnRateDO, then
// forwards the upgrade to the room DO. All non-WS requests get a 404.

import {
  ConnRateDO,
  CONN_RATE_LIMIT_PER_IP,
  CONN_RATE_LIMIT_PER_UG,
  CONN_RATE_WINDOW_MS,
} from "./conn-rate-do";
import { RoomDO } from "./room-do";

export { ConnRateDO, RoomDO };

// Env is generated by `wrangler types` into worker-configuration.d.ts.

const SUPPORTED_PROTOCOL_VERSIONS = new Set([1]);

const AccessReason = {
  Ok: "ok",
  UnknownUser: "unknown_user",
  TierNotAllowed: "tier_not_allowed",
  MultiplayerDisabled: "multiplayer_disabled",
  UsageThrottled: "usage_throttled",
  RateLimited: "rate_limited",
  MissingParams: "missing_params",
  UnsupportedProtocolVersion: "unsupported_protocol_version",
  NotAllowed: "not_allowed",
  CheckUnavailable: "check_unavailable",
} as const;

type AccessReason = (typeof AccessReason)[keyof typeof AccessReason];
type CheckDeniedReason =
  | typeof AccessReason.UnknownUser
  | typeof AccessReason.TierNotAllowed
  | typeof AccessReason.MultiplayerDisabled
  | typeof AccessReason.UsageThrottled
  | typeof AccessReason.NotAllowed;

type AccessDecision =
  | { allowed: true; reason: typeof AccessReason.Ok }
  | { allowed: false; reason: CheckDeniedReason | typeof AccessReason.CheckUnavailable };

// Positive cache TTL. After this a cached user is "stale" — still served from
// last-good, but a background refresh fires (see stale-while-revalidate below).
const POSITIVE_TTL_MS = 60_000;

// /check is given a short edge cacheTtl so bursts of true-misses for the same
// user collapse onto one origin hit.
const CHECK_CACHE_TTL_SECONDS = 30;

// Isolate-global positive cache. There is intentionally NO negative cache:
// a "not allowed" answer is never remembered, so an unsubscribe/resubscribe
// takes effect on the very next true-miss check. Abuse from the resulting
// uncached re-checks is bounded by ConnRateDO.
const positiveCache = new Map<string, { expiresAt: number }>();

// Accept the WS upgrade then immediately close with the given code/reason.
// Used for failures that occur after the upgrade decision but before we hand
// control to the DO — clients always see a WS close instead of a surprise
// HTTP error.
function acceptAndClose(code: number, reason: string): Response {
  const pair = new WebSocketPair();
  const server = pair[1];
  server.accept();
  server.close(code, reason);
  return new Response(null, { status: 101, webSocket: pair[0] });
}

function json(data: unknown, init: ResponseInit = {}): Response {
  const headers = new Headers(init.headers);
  headers.set("Cache-Control", "no-store");
  return Response.json(data, {
    ...init,
    headers,
  });
}

function withDiagnosticCors(response: Response): Response {
  const headers = new Headers(response.headers);
  headers.set("Access-Control-Allow-Origin", "*");
  headers.set("Access-Control-Allow-Methods", "GET, OPTIONS");
  headers.set("Access-Control-Allow-Headers", "Content-Type");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

function diagnosticOptions(): Response {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      "Cache-Control": "no-store",
    },
  });
}

function diagnosticMessage(reason: AccessReason): string {
  switch (reason) {
    case AccessReason.Ok:
      return "Multiplayer relay access is enabled.";
    case AccessReason.MissingParams:
      return "This game is missing Ziva multiplayer settings. Re-enable multiplayer in Ziva Settings > Ziva Cloud, then export the game again.";
    case AccessReason.UnsupportedProtocolVersion:
      return "This game was exported with an unsupported Ziva multiplayer protocol version. Update Ziva and export the game again.";
    case AccessReason.RateLimited:
      return "Too many multiplayer connection attempts were made recently. Wait a minute and try again.";
    case AccessReason.UnknownUser:
      return "This multiplayer user is not recognized by Ziva. Re-enable multiplayer in Ziva Settings > Ziva Cloud, then export the game again.";
    case AccessReason.TierNotAllowed:
      return "Your current Ziva subscription tier does not include multiplayer. Upgrade to Basic or above, then try again.";
    case AccessReason.MultiplayerDisabled:
      return "Multiplayer is not enabled for this Ziva account. Open Ziva Settings > Ziva Cloud and enable multiplayer.";
    case AccessReason.UsageThrottled:
      return "This account has reached its multiplayer bandwidth limit for the month. Wait for the limit to reset or upgrade your plan.";
    case AccessReason.CheckUnavailable:
      return "Ziva could not verify multiplayer access right now. Try again shortly.";
    case AccessReason.NotAllowed:
      return "Ziva did not allow this multiplayer connection. Check your subscription, multiplayer setting, and account status.";
  }
}

function normalizeCheckReason(reason: unknown): CheckDeniedReason {
  switch (reason) {
    case AccessReason.UnknownUser:
    case AccessReason.TierNotAllowed:
    case AccessReason.MultiplayerDisabled:
    case AccessReason.UsageThrottled:
      return reason;
    default:
      return AccessReason.NotAllowed;
  }
}

// One /check round-trip. Throws on transport failure (caller decides how to
// degrade); returns the structured access decision on a clean response.
async function fetchAccessDecision(env: Env, userId: string): Promise<AccessDecision> {
  // Staging apps/web sits behind Vercel deployment protection, so this
  // server-to-server call must carry a protection-bypass token. The var is set
  // ONLY on staging; prod apps/web is public, leaves it unset, and sends nothing.
  const bypassToken = (env as { ZIVA_API_BYPASS?: string }).ZIVA_API_BYPASS;
  const bypass = bypassToken
    ? `&x-vercel-protection-bypass=${encodeURIComponent(bypassToken)}`
    : "";
  const res = await fetch(
    `${env.ZIVA_API_BASE}/api/multiplayer/check?u=${encodeURIComponent(userId)}${bypass}`,
    { cf: { cacheTtl: CHECK_CACHE_TTL_SECONDS } },
  );
  if (!res.ok) {
    throw new Error(`check returned ${res.status}`);
  }
  const body = (await res.json()) as { allowed?: unknown; reason?: unknown };
  if (body.allowed === true) {
    return { allowed: true, reason: AccessReason.Ok };
  }
  return { allowed: false, reason: normalizeCheckReason(body.reason) };
}

// Decide whether `userId` may connect, applying stale-while-revalidate against
// the isolate-global positive cache. Returns true to allow, false to deny.
//
// - fresh hit                  → allow, no fetch
// - stale (expired) hit        → allow immediately; refresh in the background
// - true miss                  → one blocking /check; cache+allow or deny
//
// Failure modes (loud, never silent):
// - /check throws on a true miss          → deny (fail CLOSED). The caller
//   maps this to close code "check_unavailable".
// - /check denies on a true miss          → deny with the exact reason from
//                                            apps/web when available.
// - /check throws but a positive entry    → serve last-good AND console.error.
//   exists (even if expired)                Keeps subscribers online through a
//                                            transient apps/web outage.
async function checkAllowed(
  env: Env,
  ctx: ExecutionContext,
  userId: string,
): Promise<AccessDecision> {
  const now = Date.now();
  const cached = positiveCache.get(userId);

  if (cached && cached.expiresAt > now) {
    return { allowed: true, reason: AccessReason.Ok };
  }

  if (cached) {
    // Stale positive entry: serve it now, revalidate out of band. The join
    // never blocks on the refresh.
    ctx.waitUntil(
      (async () => {
        try {
          const decision = await fetchAccessDecision(env, userId);
          if (decision.allowed) {
            positiveCache.set(userId, { expiresAt: Date.now() + POSITIVE_TTL_MS });
          } else {
            // Access revoked while cached — drop so the next attempt is a
            // true miss and gets denied.
            positiveCache.delete(userId);
          }
        } catch (err) {
          // Refresh failed; keep last-good so the user isn't kicked on a blip.
          console.error(
            `multiplayer check refresh failed for ${userId}: ${(err as Error).message}`,
          );
        }
      })(),
    );
    return { allowed: true, reason: AccessReason.Ok };
  }

  // True miss — blocking check.
  try {
    const decision = await fetchAccessDecision(env, userId);
    if (decision.allowed) {
      positiveCache.set(userId, { expiresAt: now + POSITIVE_TTL_MS });
      return decision;
    }
    return decision;
  } catch (err) {
    // True miss + transport failure: fail CLOSED. We have no last-good to
    // fall back to and must never let an unverified user in.
    console.error(
      `multiplayer check failed (no cached entry) for ${userId}: ${(err as Error).message}`,
    );
    return { allowed: false, reason: AccessReason.CheckUnavailable };
  }
}

// Parse the room id out of the `/r/<room>` path segment.
function parseRoomId(url: URL): string | null {
  const parts = url.pathname.split("/").filter((p) => p.length > 0);
  if (parts.length >= 2 && parts[0] === "r") {
    return decodeURIComponent(parts[1]);
  }
  return null;
}

// Bound raw connection attempts before any /check fan-out. Keyed per-IP and
// per-(u,g); either window tripping rejects the attempt.
async function withinConnRate(
  env: Env,
  ip: string,
  userId: string,
  gameId: string,
): Promise<boolean> {
  const ipStub = env.CONN_RATE.getByName(`ip:${ip}`);
  const ugStub = env.CONN_RATE.getByName(`ug:${userId}:${gameId}`);
  const [ipOk, ugOk] = await Promise.all([
    ipStub.hit(CONN_RATE_LIMIT_PER_IP, CONN_RATE_WINDOW_MS),
    ugStub.hit(CONN_RATE_LIMIT_PER_UG, CONN_RATE_WINDOW_MS),
  ]);
  return ipOk && ugOk;
}

async function diagnose(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  const versionRaw = url.searchParams.get("v");
  const version = versionRaw === null ? 1 : Number(versionRaw);
  const userId = url.searchParams.get("u");
  const gameId = url.searchParams.get("g");

  if (!Number.isInteger(version) || !SUPPORTED_PROTOCOL_VERSIONS.has(version)) {
    return json({
      ok: false,
      reason: AccessReason.UnsupportedProtocolVersion,
      message: diagnosticMessage(AccessReason.UnsupportedProtocolVersion),
    });
  }

  if (!userId || !gameId) {
    return json(
      {
        ok: false,
        reason: AccessReason.MissingParams,
        message: diagnosticMessage(AccessReason.MissingParams),
      },
      { status: 400 },
    );
  }

  const ip = request.headers.get("CF-Connecting-IP") ?? "unknown";
  if (!(await withinConnRate(env, ip, userId, gameId))) {
    return json({
      ok: false,
      reason: AccessReason.RateLimited,
      message: diagnosticMessage(AccessReason.RateLimited),
    });
  }

  try {
    const decision = await fetchAccessDecision(env, userId);
    return json({
      ok: decision.allowed,
      reason: decision.reason,
      message: diagnosticMessage(decision.reason),
    });
  } catch (err) {
    console.error(
      `multiplayer diagnostic check failed for ${userId}: ${(err as Error).message}`,
    );
    return json(
      {
        ok: false,
        reason: AccessReason.CheckUnavailable,
        message: diagnosticMessage(AccessReason.CheckUnavailable),
      },
      { status: 503 },
    );
  }
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/diagnose") {
      if (request.method === "OPTIONS") {
        return diagnosticOptions();
      }
      return withDiagnosticCors(await diagnose(request, env));
    }

    if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
      return new Response("ziva-multiplayer relay — websocket only", { status: 404 });
    }

    const versionRaw = url.searchParams.get("v");
    const version = versionRaw === null ? 1 : Number(versionRaw);
    if (!Number.isInteger(version) || !SUPPORTED_PROTOCOL_VERSIONS.has(version)) {
      return acceptAndClose(1008, AccessReason.UnsupportedProtocolVersion);
    }

    const userId = url.searchParams.get("u");
    const gameId = url.searchParams.get("g");
    const room = parseRoomId(url);
    if (!userId || !gameId || !room) {
      return acceptAndClose(1008, AccessReason.MissingParams);
    }

    // Bound raw attempts FIRST so the no-negative-cache /check below can't be
    // weaponized into unbounded origin fan-out.
    const ip = request.headers.get("CF-Connecting-IP") ?? "unknown";
    if (!(await withinConnRate(env, ip, userId, gameId))) {
      return acceptAndClose(1008, AccessReason.RateLimited);
    }

    const decision = await checkAllowed(env, ctx, userId);
    if (!decision.allowed) {
      return acceptAndClose(1008, decision.reason);
    }

    // RoomDO is named by room id — same room id always lands on the same DO
    // instance globally.
    const stub = env.ROOM.getByName(room);

    // Forward the upgrade. The DO trusts these headers because only this
    // Worker (same script binding) can set them.
    const upstreamReq = new Request(request.url, request);
    upstreamReq.headers.set("X-Ziva-Sub", userId);
    upstreamReq.headers.set("X-Ziva-Game", gameId);
    upstreamReq.headers.set("X-Ziva-Rid", room);
    upstreamReq.headers.set("X-Ziva-Version", String(version));

    return stub.fetch(upstreamReq);
  },
} satisfies ExportedHandler<Env>;
