// Worker entry point.
//
// Terminates the WebSocket upgrade, verifies the JWT, derives the room DO,
// and forwards the upgrade to the DO. All non-WS requests get a 404.

import { jwtVerify } from "jose";

import { RoomDO } from "./room-do";

export { RoomDO };

// Env is generated by `wrangler types` into worker-configuration.d.ts.

const SUPPORTED_PROTOCOL_VERSIONS = new Set([1]);

interface JwtPayload {
  sub: string;
  rid: string;
  tier: string;
  iat: number;
  exp: number;
}

// Accept the WS upgrade then immediately close with the given code/reason.
// Used for failures that occur after the upgrade decision but before we
// hand control to the DO — clients always see a WS close instead of a
// surprise HTTP error.
function acceptAndClose(code: number, reason: string): Response {
  const pair = new WebSocketPair();
  const server = pair[1];
  server.accept();
  server.close(code, reason);
  return new Response(null, { status: 101, webSocket: pair[0] });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
      return new Response("ziva-multiplayer relay — websocket only", { status: 404 });
    }

    const url = new URL(request.url);
    const versionRaw = url.searchParams.get("v");
    const version = versionRaw === null ? 1 : Number(versionRaw);
    if (!Number.isInteger(version) || !SUPPORTED_PROTOCOL_VERSIONS.has(version)) {
      return acceptAndClose(1008, "unsupported_protocol_version");
    }

    const token = url.searchParams.get("token");
    if (!token) {
      return new Response("missing_token", { status: 401 });
    }

    let claims: JwtPayload;
    try {
      const secret = new TextEncoder().encode(env.MULTIPLAYER_JWT_SECRET);
      const verified = await jwtVerify(token, secret, { algorithms: ["HS256"] });
      const p = verified.payload as Partial<JwtPayload> & Record<string, unknown>;
      if (typeof p.sub !== "string" || typeof p.rid !== "string" || typeof p.tier !== "string") {
        return new Response("invalid_claims", { status: 401 });
      }
      claims = {
        sub: p.sub,
        rid: p.rid,
        tier: p.tier,
        iat: typeof p.iat === "number" ? p.iat : 0,
        exp: typeof p.exp === "number" ? p.exp : 0,
      };
    } catch (err) {
      // jose throws JWTExpired, JWSInvalid, JWSSignatureVerificationFailed, etc.
      return new Response(`invalid_token:${(err as Error).name}`, { status: 401 });
    }

    // RoomDO is named by room id (rid claim) — same room id always lands on
    // the same DO instance globally.
    const stub = env.ROOM.getByName(claims.rid);

    // Forward the upgrade. The DO sees the original request unchanged so it
    // can read the query string and headers itself if it needs to.
    // We pass the verified claims via custom headers — the DO trusts these
    // headers because only this Worker (same script binding) can set them.
    const upstreamReq = new Request(request.url, request);
    upstreamReq.headers.set("X-Ziva-Sub", claims.sub);
    upstreamReq.headers.set("X-Ziva-Rid", claims.rid);
    upstreamReq.headers.set("X-Ziva-Tier", claims.tier);
    upstreamReq.headers.set("X-Ziva-Version", String(version));

    return stub.fetch(upstreamReq);
  },
} satisfies ExportedHandler<Env>;
