// RoomDO — one Durable Object per multiplayer room.
//
// Speaks Godot's WebSocketMultiplayerPeer wire protocol directly so vanilla
// Godot clients can connect with `WebSocketMultiplayerPeer.create_client(url)`
// and `@rpc` works end-to-end. See src/proto/v1.ts for the binary layout.
//
// Uses the Hibernation API (`state.acceptWebSocket`) so idle rooms cost
// nothing while still preserving per-connection state across hibernation.
// State that must survive hibernation lives in WebSocket attachments
// (acknowledged-stable via `serializeAttachment`/`deserializeAttachment`).
//
// Per-instance state (peer counter, room cap, rate limit windows) is held
// in SQLite — the DO can be evicted at any time and re-created with the
// counter intact.

import { DurableObject } from "cloudflare:workers";

import { CapState, THROTTLED_BYTES_PER_SEC } from "./cap-state";
import {
  addPeerPacket,
  assignedPeerId,
  delPeerPacket,
  isAuthPacket,
  isRelayPacket,
  parseRelayHeader,
  rewriteRelaySender,
} from "./proto/v1";

// Env is generated by `wrangler types` into worker-configuration.d.ts.

const ROOM_CAP = 32;
const RATE_LIMIT_MSGS_PER_SEC = 60;
const RATE_LIMIT_BYTES_PER_SEC = 32 * 1024;
const RATE_WINDOW_MS = 1000;

// Stored on each WebSocket attachment so we can recover identity after
// hibernation without round-tripping to storage.
interface SocketMeta {
  peerId: number;
  devUserId: string;
  roomId: string;
  // Sliding window for rate limiting. Reset whenever windowStart is >1s ago.
  windowStart: number;
  windowMsgs: number;
  windowBytes: number;
  // Per-connection byte-budget; lowered to THROTTLED_BYTES_PER_SEC when the
  // owner devUserId is in the throttle set.
  byteBudget: number;
  // Cumulative bytes routed FOR THIS CONNECTION, both directions. Emitted on
  // close so the rollup cron can attribute totals to the right user. Snapshot
  // is bounded by AE write rate so we only emit per-window aggregates, not
  // per-message rows.
  totalBytesIn: number;
  totalBytesOut: number;
}

export class RoomDO extends DurableObject<Env> {
  private capState: CapState | null;
  private roomId = "";

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    // env.CAPS_KV is optional in local/test envs that don't bind it. When
    // absent we treat no user as throttled (the cap check still happens in
    // the JWT issuer).
    this.capState = env.CAPS_KV ? new CapState(env.CAPS_KV) : null;
    ctx.blockConcurrencyWhile(async () => {
      // Prime the throttle cache before accepting connections so the first
      // fetch() sees authoritative state. The DO will not handle any
      // requests until this resolves.
      if (this.capState) {
        await this.capState.refresh();
      }
      // peer_counter is the source of truth for next peer id assignment.
      // It's monotonic across hibernation; we never reuse ids. Starts at 1
      // because the server is the implicit id=1 in Godot's model; the first
      // real client gets id=2.
      ctx.storage.sql.exec(`
        CREATE TABLE IF NOT EXISTS room_state (
          key TEXT PRIMARY KEY,
          value INTEGER NOT NULL
        )
      `);
      const existing = ctx.storage.sql
        .exec<{ value: number }>(
          "SELECT value FROM room_state WHERE key = 'peer_counter'",
        )
        .toArray();
      if (existing.length === 0) {
        ctx.storage.sql.exec(
          "INSERT INTO room_state (key, value) VALUES ('peer_counter', 1)",
        );
      }
    });
  }

  // Worker forwards every WS upgrade here.
  async fetch(request: Request): Promise<Response> {
    if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
      return new Response("expected websocket", { status: 426 });
    }

    const devUserId = request.headers.get("X-Ziva-Sub");
    const roomId = request.headers.get("X-Ziva-Rid");
    if (!devUserId || !roomId) {
      // Worker forgot to set the trusted headers — fail loudly so the bug
      // is obvious in dev. Should never happen in prod.
      return new Response("missing_trusted_headers", { status: 500 });
    }
    this.roomId = roomId;

    // Enforce room cap. getWebSockets() counts currently-attached hibernated
    // and active sockets, which is exactly what we want.
    const current = this.ctx.getWebSockets().length;
    if (current >= ROOM_CAP) {
      const pair = new WebSocketPair();
      pair[1].accept();
      pair[1].close(1008, "room_full");
      return new Response(null, { status: 101, webSocket: pair[0] });
    }

    const peerId = this.nextPeerId();
    const isFirstPeer = current === 0;

    // Check throttle status BEFORE accepting the socket — if the user blew
    // their hard cap the JWT issuer should already 403, so this is a defense
    // in depth (the KV-cached set may be stale by minutes).
    if (this.capState) {
      this.capState.isThrottled(devUserId); // primes the cache
    }
    const throttled =
      this.capState !== null && this.capState.isThrottled(devUserId);
    const byteBudget = throttled ? THROTTLED_BYTES_PER_SEC : RATE_LIMIT_BYTES_PER_SEC;

    const pair = new WebSocketPair();
    const server = pair[1];

    const meta: SocketMeta = {
      peerId,
      devUserId,
      roomId,
      windowStart: Date.now(),
      windowMsgs: 0,
      windowBytes: 0,
      byteBudget,
      totalBytesIn: 0,
      totalBytesOut: 0,
    };
    // serializeAttachment stores arbitrary structured-cloneable data per
    // socket. Survives hibernation; we read it back in webSocketMessage.
    server.serializeAttachment(meta);

    // acceptWebSocket registers the socket for hibernation routing — the DO
    // can be evicted and the runtime will re-dispatch messages to the class.
    this.ctx.acceptWebSocket(server);

    // First packet from server to client: 4 raw bytes = LE int32 peer_id.
    // Godot client reads this in WebSocketMultiplayerPeer::_poll_client.
    server.send(assignedPeerId(peerId));

    // Now tell every existing peer about the newcomer AND tell the newcomer
    // about every existing peer. Mirrors SceneMultiplayer::_admit_peer
    // (modules/multiplayer/scene_multiplayer.cpp:368-395).
    const newJoinPacket = addPeerPacket(peerId);
    for (const peer of this.ctx.getWebSockets()) {
      if (peer === server) continue;
      const existing = peer.deserializeAttachment() as SocketMeta | null;
      if (!existing) continue;
      try {
        // Tell the existing peer about the newcomer.
        peer.send(newJoinPacket);
        // Tell the newcomer about the existing peer.
        server.send(addPeerPacket(existing.peerId));
      } catch {
        // Peer's socket is in a bad state — webSocketClose will clean up.
      }
    }

    if (isFirstPeer) {
      this.emitEvent({
        event_type: "room_created",
        devUserId,
        roomId,
        bytesIn: 0,
        bytesOut: 0,
        peerCount: 1,
      });
    }
    this.emitEvent({
      event_type: "peer_joined",
      devUserId,
      roomId,
      bytesIn: 0,
      bytesOut: 0,
      peerCount: this.ctx.getWebSockets().length,
      extra: { peerId, throttled },
    });

    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  async webSocketMessage(ws: WebSocket, message: string | ArrayBuffer): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (!meta) {
      // No attachment means the socket somehow bypassed fetch(). Close it.
      ws.close(1011, "missing_attachment");
      return;
    }

    const now = Date.now();
    const byteSize =
      typeof message === "string"
        ? new TextEncoder().encode(message).byteLength
        : message.byteLength;

    // Sliding 1-second window. Reset counters when the window has expired.
    if (now - meta.windowStart >= RATE_WINDOW_MS) {
      meta.windowStart = now;
      meta.windowMsgs = 0;
      meta.windowBytes = 0;
    }
    meta.windowMsgs += 1;
    meta.windowBytes += byteSize;
    meta.totalBytesIn += byteSize;

    if (
      meta.windowMsgs > RATE_LIMIT_MSGS_PER_SEC ||
      meta.windowBytes > meta.byteBudget
    ) {
      this.emitEvent({
        event_type: "rate_limit_hit",
        devUserId: meta.devUserId,
        roomId: meta.roomId,
        bytesIn: byteSize,
        bytesOut: 0,
        peerCount: this.ctx.getWebSockets().length,
        extra: { peerId: meta.peerId, budget: meta.byteBudget },
      });
      ws.serializeAttachment(meta);
      ws.close(1008, "rate_limit_exceeded");
      return;
    }

    // Strings are not part of the Godot protocol — anything text on this
    // socket is a bug in the sender. Drop it loudly so it's debuggable.
    if (typeof message === "string") {
      ws.serializeAttachment(meta);
      this.emitEvent({
        event_type: "text_frame_dropped",
        devUserId: meta.devUserId,
        roomId: meta.roomId,
        bytesIn: byteSize,
        bytesOut: 0,
        peerCount: this.ctx.getWebSockets().length,
        extra: { peerId: meta.peerId },
      });
      return;
    }

    const view = new Uint8Array(message);
    let bytesOutTotal = 0;

    // SYS_COMMAND_RELAY — parse the target peer and route. SceneMultiplayer
    // generates these for every @rpc / SYNC / SPAWN. The Worker rewrites
    // the sender_id in the relay header and forwards the inner payload
    // unchanged.
    if (isRelayPacket(view)) {
      const header = parseRelayHeader(view);
      const out = rewriteRelaySender(view, meta.peerId);

      if (header.targetPeer > 0) {
        // Unicast.
        for (const peer of this.ctx.getWebSockets()) {
          if (peer === ws) continue;
          const m = peer.deserializeAttachment() as SocketMeta | null;
          if (!m || m.peerId !== header.targetPeer) continue;
          try {
            peer.send(out);
            bytesOutTotal += out.byteLength;
            m.totalBytesOut += out.byteLength;
            peer.serializeAttachment(m);
          } catch {
            // Bad socket — its own webSocketClose handles cleanup.
          }
          break;
        }
      } else {
        // Broadcast. target=0 → all-except-sender. target=-N → all-except-sender-and-N.
        const exclude = header.targetPeer === 0 ? null : -header.targetPeer;
        for (const peer of this.ctx.getWebSockets()) {
          if (peer === ws) continue;
          const m = peer.deserializeAttachment() as SocketMeta | null;
          if (!m) continue;
          if (exclude !== null && m.peerId === exclude) continue;
          try {
            peer.send(out);
            bytesOutTotal += out.byteLength;
            m.totalBytesOut += out.byteLength;
            peer.serializeAttachment(m);
          } catch {
            // Bad socket — its own webSocketClose handles cleanup.
          }
        }
      }

      meta.totalBytesOut += 0; // sender's own bytes-out is from receiving replies
      ws.serializeAttachment(meta);

      this.emitEvent({
        event_type: "relay",
        devUserId: meta.devUserId,
        roomId: meta.roomId,
        bytesIn: byteSize,
        bytesOut: bytesOutTotal,
        peerCount: this.ctx.getWebSockets().length,
      });
      return;
    }

    // SYS_COMMAND_AUTH — pure peer-to-peer handshake. Broadcast to everyone
    // else; the Worker has no opinion on its contents.
    if (isAuthPacket(view)) {
      for (const peer of this.ctx.getWebSockets()) {
        if (peer === ws) continue;
        try {
          peer.send(view);
          bytesOutTotal += view.byteLength;
          const m = peer.deserializeAttachment() as SocketMeta | null;
          if (m) {
            m.totalBytesOut += view.byteLength;
            peer.serializeAttachment(m);
          }
        } catch {
          // Bad socket — its own webSocketClose handles cleanup.
        }
      }

      ws.serializeAttachment(meta);
      this.emitEvent({
        event_type: "auth",
        devUserId: meta.devUserId,
        roomId: meta.roomId,
        bytesIn: byteSize,
        bytesOut: bytesOutTotal,
        peerCount: this.ctx.getWebSockets().length,
      });
      return;
    }

    // Anything else (raw NETWORK_COMMAND_REMOTE_CALL etc sent directly,
    // without a RELAY wrapper) shouldn't happen with the standard Godot
    // SceneMultiplayer client — but log + drop instead of crashing so we
    // see the problem during dev.
    const cmdLow = view.length > 0 ? view[0] & 0x7 : -1;
    ws.serializeAttachment(meta);
    this.emitEvent({
      event_type: "unknown_packet_dropped",
      devUserId: meta.devUserId,
      roomId: meta.roomId,
      bytesIn: byteSize,
      bytesOut: 0,
      peerCount: this.ctx.getWebSockets().length,
      extra: {
        peerId: meta.peerId,
        cmd: cmdLow,
        sub: view.length > 1 ? view[1] : -1,
        size: view.byteLength,
      },
    });
  }

  async webSocketClose(
    ws: WebSocket,
    code: number,
    reason: string,
    _wasClean: boolean,
  ): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (meta) {
      // Notify remaining peers so they can update their membership view.
      const leaveFrame = delPeerPacket(meta.peerId);
      let bytesOutTotal = 0;
      for (const peer of this.ctx.getWebSockets()) {
        if (peer === ws) continue;
        try {
          peer.send(leaveFrame);
          bytesOutTotal += leaveFrame.byteLength;
          const m = peer.deserializeAttachment() as SocketMeta | null;
          if (m) {
            m.totalBytesOut += leaveFrame.byteLength;
            peer.serializeAttachment(m);
          }
        } catch {
          // Peer's socket is gone — its own webSocketClose handles cleanup.
        }
      }
      // Emit per-connection totals so the rollup attributes lifetime traffic
      // to this user. bytesIn = sum of bytes this peer sent; bytesOut = sum of
      // bytes this peer received from others (accumulated by the sender's
      // routing loop).
      this.emitEvent({
        event_type: "peer_left",
        devUserId: meta.devUserId,
        roomId: meta.roomId,
        bytesIn: meta.totalBytesIn,
        bytesOut: meta.totalBytesOut,
        peerCount: Math.max(0, this.ctx.getWebSockets().length - 1),
        extra: { peerId: meta.peerId, code, reason, broadcastBytes: bytesOutTotal },
      });
    }
    // Ensure the socket is fully closed even if the close came from the peer.
    try {
      ws.close(code, reason);
    } catch {
      // Already closed.
    }
    this.maybeEmitRoomClosed();
  }

  async webSocketError(ws: WebSocket, error: unknown): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (meta) {
      this.emitEvent({
        event_type: "peer_error",
        devUserId: meta.devUserId,
        roomId: meta.roomId,
        bytesIn: 0,
        bytesOut: 0,
        peerCount: this.ctx.getWebSockets().length,
        extra: {
          peerId: meta.peerId,
          error: String((error as Error)?.message ?? error),
        },
      });
    }
    this.maybeEmitRoomClosed();
  }

  // ---- internals ----

  private nextPeerId(): number {
    // UPDATE...RETURNING is atomic in SQLite; coalesced with no awaits between
    // so the read+write commits as one transaction. Counter is seeded at 1
    // (server's implicit id) so the first real client gets id=2 — matches
    // the >=2 invariant Godot enforces in websocket_multiplayer_peer.cpp.
    const row = this.ctx.storage.sql
      .exec<{ value: number }>(
        "UPDATE room_state SET value = value + 1 WHERE key = 'peer_counter' RETURNING value",
      )
      .one();
    return row.value;
  }

  private maybeEmitRoomClosed(): void {
    const remaining = this.ctx.getWebSockets().length;
    if (remaining === 0) {
      this.emitEvent({
        event_type: "room_closed",
        devUserId: "",
        roomId: this.roomId,
        bytesIn: 0,
        bytesOut: 0,
        peerCount: 0,
      });
    }
  }

  private emitEvent(ev: {
    event_type: string;
    devUserId: string;
    roomId: string;
    bytesIn: number;
    bytesOut: number;
    peerCount: number;
    extra?: Record<string, unknown>;
  }): void {
    // Console log doubles as observable signal in `wrangler tail` and in tests.
    console.log(
      JSON.stringify({
        event: ev.event_type,
        devUserId: ev.devUserId,
        roomId: ev.roomId,
        bytesIn: ev.bytesIn,
        bytesOut: ev.bytesOut,
        peerCount: ev.peerCount,
        ...(ev.extra ?? {}),
      }),
    );

    // Analytics Engine — prod sink the rollup cron reads from. Schema:
    //   blobs[0]: event_type
    //   blobs[1]: devUserId  (the user being billed)
    //   blobs[2]: roomId
    //   doubles[0]: bytesIn
    //   doubles[1]: bytesOut
    //   doubles[2]: peerCount
    //   indexes[0]: devUserId — AE allows ONE index per data point and we
    //     query "SUM(bytes) GROUP BY devUserId" so this is the right choice.
    // The binding is optional — present only when AE is enabled on the
    // account (see wrangler.toml comments). Cast through unknown so tsc
    // compiles whether or not `MULTIPLAYER_EVENTS` is in the Env type.
    const events = (this.env as unknown as { MULTIPLAYER_EVENTS?: AnalyticsEngineDataset })
      .MULTIPLAYER_EVENTS;
    if (events) {
      try {
        events.writeDataPoint({
          blobs: [ev.event_type, ev.devUserId, ev.roomId],
          doubles: [ev.bytesIn, ev.bytesOut, ev.peerCount],
          indexes: [ev.devUserId],
        });
      } catch (err) {
        console.log(
          JSON.stringify({
            event: "ae_write_error",
            error: String((err as Error).message ?? err),
          }),
        );
      }
    }

    // Mirror to the log-drain pipeline so the existing Cloudflare Worker that
    // tails logs can ingest these events alongside web logs. Fire-and-forget.
    const drainUrl = this.env.LOG_DRAIN_URL;
    if (drainUrl) {
      // ctx.waitUntil keeps the fetch alive after the handler returns without
      // blocking message delivery.
      this.ctx.waitUntil(
        fetch(drainUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            event: ev.event_type,
            devUserId: ev.devUserId,
            roomId: ev.roomId,
            bytesIn: ev.bytesIn,
            bytesOut: ev.bytesOut,
            peerCount: ev.peerCount,
            ts: Date.now(),
            ...(ev.extra ?? {}),
          }),
        }).catch((err) => {
          console.log(
            JSON.stringify({
              event: "log_drain_post_error",
              error: String((err as Error).message ?? err),
            }),
          );
        }),
      );
    }
  }
}
