// RoomDO — one Durable Object per multiplayer room.
//
// Uses the Hibernation API (`state.acceptWebSocket`) so idle rooms cost
// nothing while still preserving per-connection state across hibernation.
// State that must survive hibernation lives in WebSocket attachments
// (acknowledged-stable via `serializeAttachment`/`deserializeAttachment`).
//
// Per-instance state (peer counter, room cap, rate limit windows) is held
// in SQLite — the DO can be evicted at any time and re-created with the
// counter intact.

import { DurableObject } from "cloudflare:workers";

import { tagSender, welcome } from "./proto/v1";

// Env is generated by `wrangler types` into worker-configuration.d.ts.

const ROOM_CAP = 32;
const RATE_LIMIT_MSGS_PER_SEC = 60;
const RATE_LIMIT_BYTES_PER_SEC = 32 * 1024;
const RATE_WINDOW_MS = 1000;

// Stored on each WebSocket attachment so we can recover identity after
// hibernation without round-tripping to storage.
interface SocketMeta {
  peerId: number;
  devUserId: string;
  // Sliding window for rate limiting. Reset whenever windowStart is >1s ago.
  windowStart: number;
  windowMsgs: number;
  windowBytes: number;
}

export class RoomDO extends DurableObject<Env> {
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    ctx.blockConcurrencyWhile(async () => {
      // peer_counter is the source of truth for next peer id assignment.
      // It's monotonic across hibernation; we never reuse ids.
      ctx.storage.sql.exec(`
        CREATE TABLE IF NOT EXISTS room_state (
          key TEXT PRIMARY KEY,
          value INTEGER NOT NULL
        )
      `);
      const existing = ctx.storage.sql
        .exec<{ value: number }>(
          "SELECT value FROM room_state WHERE key = 'peer_counter'",
        )
        .toArray();
      if (existing.length === 0) {
        ctx.storage.sql.exec(
          "INSERT INTO room_state (key, value) VALUES ('peer_counter', 0)",
        );
      }
    });
  }

  // Worker forwards every WS upgrade here.
  async fetch(request: Request): Promise<Response> {
    if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
      return new Response("expected websocket", { status: 426 });
    }

    const devUserId = request.headers.get("X-Ziva-Sub");
    const roomId = request.headers.get("X-Ziva-Rid");
    if (!devUserId || !roomId) {
      // Worker forgot to set the trusted headers — fail loudly so the bug
      // is obvious in dev. Should never happen in prod.
      return new Response("missing_trusted_headers", { status: 500 });
    }

    // Enforce room cap. getWebSockets() counts currently-attached hibernated
    // and active sockets, which is exactly what we want.
    const current = this.ctx.getWebSockets().length;
    if (current >= ROOM_CAP) {
      const pair = new WebSocketPair();
      pair[1].accept();
      pair[1].close(1008, "room_full");
      return new Response(null, { status: 101, webSocket: pair[0] });
    }

    const peerId = this.nextPeerId();

    const pair = new WebSocketPair();
    const server = pair[1];

    const meta: SocketMeta = {
      peerId,
      devUserId,
      windowStart: Date.now(),
      windowMsgs: 0,
      windowBytes: 0,
    };
    // serializeAttachment stores arbitrary structured-cloneable data per
    // socket. Survives hibernation; we read it back in webSocketMessage.
    server.serializeAttachment(meta);

    // acceptWebSocket registers the socket for hibernation routing — the DO
    // can be evicted and the runtime will re-dispatch messages to the class.
    this.ctx.acceptWebSocket(server);

    // Send welcome envelope. Done after accept so the client always sees it.
    server.send(welcome(peerId));

    this.logEvent("peer_join", { peerId, devUserId });

    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  async webSocketMessage(ws: WebSocket, message: string | ArrayBuffer): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (!meta) {
      // No attachment means the socket somehow bypassed fetch(). Close it.
      ws.close(1011, "missing_attachment");
      return;
    }

    const now = Date.now();
    const byteSize =
      typeof message === "string"
        ? new TextEncoder().encode(message).byteLength
        : message.byteLength;

    // Sliding 1-second window. Reset counters when the window has expired.
    if (now - meta.windowStart >= RATE_WINDOW_MS) {
      meta.windowStart = now;
      meta.windowMsgs = 0;
      meta.windowBytes = 0;
    }
    meta.windowMsgs += 1;
    meta.windowBytes += byteSize;

    if (
      meta.windowMsgs > RATE_LIMIT_MSGS_PER_SEC ||
      meta.windowBytes > RATE_LIMIT_BYTES_PER_SEC
    ) {
      this.logEvent("rate_limit", { peerId: meta.peerId });
      ws.close(1008, "rate_limit_exceeded");
      return;
    }

    ws.serializeAttachment(meta);

    // Broadcast to every other peer in the room.
    const out =
      typeof message === "string" ? tagSender(message, meta.peerId) : message;

    for (const peer of this.ctx.getWebSockets()) {
      if (peer === ws) continue;
      try {
        peer.send(out);
      } catch {
        // Peer's socket is in a bad state — let webSocketClose handle cleanup
        // when it fires for that socket. Don't fail the broadcast.
      }
    }
  }

  async webSocketClose(
    ws: WebSocket,
    code: number,
    reason: string,
    _wasClean: boolean,
  ): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (meta) {
      this.logEvent("peer_leave", { peerId: meta.peerId, code, reason });
    }
    // Ensure the socket is fully closed even if the close came from the peer.
    try {
      ws.close(code, reason);
    } catch {
      // Already closed.
    }
    this.maybeLogRoomClosed();
  }

  async webSocketError(ws: WebSocket, error: unknown): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (meta) {
      this.logEvent("peer_error", {
        peerId: meta.peerId,
        error: String((error as Error)?.message ?? error),
      });
    }
    this.maybeLogRoomClosed();
  }

  // ---- internals ----

  private nextPeerId(): number {
    // UPDATE...RETURNING is atomic in SQLite; coalesced with no awaits between
    // so the read+write commits as one transaction.
    const row = this.ctx.storage.sql
      .exec<{ value: number }>(
        "UPDATE room_state SET value = value + 1 WHERE key = 'peer_counter' RETURNING value",
      )
      .one();
    return row.value;
  }

  private maybeLogRoomClosed(): void {
    const remaining = this.ctx.getWebSockets().length;
    if (remaining === 0) {
      this.logEvent("room_closed", {});
    }
  }

  private logEvent(name: string, extra: Record<string, unknown>): void {
    // Console log doubles as observable signal in `wrangler tail` and in tests
    // (vitest captures console output). Analytics Engine is the prod sink.
    console.log(JSON.stringify({ event: name, ...extra }));
    try {
      this.env.MULTIPLAYER_EVENTS.writeDataPoint({
        blobs: [name, JSON.stringify(extra)],
        doubles: [Date.now()],
        indexes: [name],
      });
    } catch {
      // Analytics Engine binding may not be available in dev — don't crash.
    }
  }
}
