// RoomDO — one Durable Object per multiplayer room.
//
// Speaks Godot's WebSocketMultiplayerPeer wire protocol directly so vanilla
// Godot clients can connect with `WebSocketMultiplayerPeer.create_client(url)`
// and `@rpc` works end-to-end. See src/proto/v1.ts for the binary layout.
//
// Uses the Hibernation API (`state.acceptWebSocket`) so idle rooms cost
// nothing while still preserving per-connection state across hibernation.
// State that must survive hibernation lives in WebSocket attachments
// (acknowledged-stable via `serializeAttachment`/`deserializeAttachment`).
//
// Per-instance state (peer counter, room cap, rate limit windows) is held
// in SQLite — the DO can be evicted at any time and re-created with the
// counter intact.

import { DurableObject } from "cloudflare:workers";

import {
  addPeerPacket,
  assignedPeerId,
  decodeStateSet,
  delPeerPacket,
  encodeStateSnapshot,
  encodeStateUpdate,
  isAuthPacket,
  isRelayPacket,
  parseRelayHeader,
  rewriteRelaySender,
  STATE_SET,
  WORLD_LOAD,
  WORLD_SAVE,
  WORLD_SAVE_ACK,
} from "./proto/v1";
import {
  SharedStateStore,
  SharedValueTooLargeError,
} from "./shared-state-store";
import { WorldStore, WorldTooLargeError } from "./world-store";

// Env is generated by `wrangler types` into worker-configuration.d.ts.

const ROOM_CAP = 32;
// Per-connection burst guard, NOT the economic limit (the monthly bandwidth cap
// is — and it bills the developer's own quota, so abuse self-limits). Sized so
// it never kicks a legit game: a host-authority game's host replicates every
// peer, so its rate scales with player count (~30 players * 30Hz ≈ 900/sec).
// 1000/sec carries a near-full room at 30Hz; beyond that the Durable Object's
// fan-out (each msg -> up to ROOM_CAP-1 peers), not this cap, is the ceiling.
const RATE_LIMIT_MSGS_PER_SEC = 1000;
const RATE_LIMIT_BYTES_PER_SEC = 1024 * 1024;
const RATE_WINDOW_MS = 1000;

// Stored on each WebSocket attachment so we can recover identity after
// hibernation without round-tripping to storage.
interface SocketMeta {
  peerId: number;
  devUserId: string;
  gameId: string;
  roomId: string;
  // Sliding window for rate limiting. Reset whenever windowStart is >1s ago.
  windowStart: number;
  windowMsgs: number;
  windowBytes: number;
  // Cumulative bytes routed FOR THIS CONNECTION, both directions. Emitted on
  // close so the rollup cron can attribute totals to the right user. Snapshot
  // is bounded by AE write rate so we only emit per-window aggregates, not
  // per-message rows.
  totalBytesIn: number;
  totalBytesOut: number;
}

export class RoomDO extends DurableObject<Env> {
  private roomId = "";
  // Lazily built so it always wraps the live storage handle. The schema is
  // created in the constructor's blockConcurrencyWhile.
  private _worldStore?: WorldStore;
  private get worldStore(): WorldStore {
    if (!this._worldStore) {
      this._worldStore = new WorldStore(this.ctx.storage.sql);
    }
    return this._worldStore;
  }

  // Live per-key shared-state doc (no-host authoritative model). Lazily built
  // so it always wraps the live storage handle; schema created in the ctor.
  private _sharedStateStore?: SharedStateStore;
  private get sharedStateStore(): SharedStateStore {
    if (!this._sharedStateStore) {
      this._sharedStateStore = new SharedStateStore(this.ctx.storage.sql);
    }
    return this._sharedStateStore;
  }

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    ctx.blockConcurrencyWhile(async () => {
      // peer_counter is the source of truth for next peer id assignment.
      // It's monotonic across hibernation; we never reuse ids. Starts at 1
      // because the server is the implicit id=1 in Godot's model; the first
      // real client gets id=2.
      ctx.storage.sql.exec(`
        CREATE TABLE IF NOT EXISTS room_state (
          key TEXT PRIMARY KEY,
          value INTEGER NOT NULL
        )
      `);
      // Per-room persisted world snapshot — survives hibernation and "all peers
      // left" because SQLite storage is durable across DO eviction. Chunked
      // across rows so multi-MB worlds clear the single-cell SQLITE_TOOBIG
      // ceiling (see world-store.ts).
      WorldStore.createTable(ctx.storage.sql);
      // Live per-key shared-state doc (no-host authoritative model). Same
      // durability story as the world store; chunked for large values.
      SharedStateStore.createTable(ctx.storage.sql);
      const existing = ctx.storage.sql
        .exec<{ value: number }>(
          "SELECT value FROM room_state WHERE key = 'peer_counter'",
        )
        .toArray();
      if (existing.length === 0) {
        ctx.storage.sql.exec(
          "INSERT INTO room_state (key, value) VALUES ('peer_counter', 1)",
        );
      }
      // Monotonic shared-state revision. Lives in the same durable counter
      // table so it never resets or reuses across eviction — a stale peer's
      // rev can never out-number a newer committed write. Starts at 0; the
      // first committed write is rev 1.
      const revRow = ctx.storage.sql
        .exec<{ value: number }>(
          "SELECT value FROM room_state WHERE key = 'state_rev'",
        )
        .toArray();
      if (revRow.length === 0) {
        ctx.storage.sql.exec(
          "INSERT INTO room_state (key, value) VALUES ('state_rev', 0)",
        );
      }
    });
  }

  // Worker forwards every WS upgrade here.
  async fetch(request: Request): Promise<Response> {
    if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
      return new Response("expected websocket", { status: 426 });
    }

    const devUserId = request.headers.get("X-Ziva-Sub");
    const gameId = request.headers.get("X-Ziva-Game");
    const roomId = request.headers.get("X-Ziva-Rid");
    if (!devUserId || !gameId || !roomId) {
      // Worker forgot to set the trusted headers — fail loudly so the bug
      // is obvious in dev. Should never happen in prod.
      return new Response("missing_trusted_headers", { status: 500 });
    }
    this.roomId = roomId;

    // Enforce room cap. getWebSockets() counts currently-attached hibernated
    // and active sockets, which is exactly what we want.
    const current = this.ctx.getWebSockets().length;
    if (current >= ROOM_CAP) {
      const pair = new WebSocketPair();
      pair[1].accept();
      pair[1].close(1008, "room_full");
      return new Response(null, { status: 101, webSocket: pair[0] });
    }

    const peerId = this.nextPeerId();
    const isFirstPeer = current === 0;

    const pair = new WebSocketPair();
    const server = pair[1];

    const meta: SocketMeta = {
      peerId,
      devUserId,
      gameId,
      roomId,
      windowStart: Date.now(),
      windowMsgs: 0,
      windowBytes: 0,
      totalBytesIn: 0,
      totalBytesOut: 0,
    };
    // serializeAttachment stores arbitrary structured-cloneable data per
    // socket. Survives hibernation; we read it back in webSocketMessage.
    server.serializeAttachment(meta);

    // acceptWebSocket registers the socket for hibernation routing — the DO
    // can be evicted and the runtime will re-dispatch messages to the class.
    this.ctx.acceptWebSocket(server);

    // First packet from server to client: 4 raw bytes = LE int32 peer_id.
    // Godot client reads this in WebSocketMultiplayerPeer::_poll_client.
    server.send(assignedPeerId(peerId));

    // Now tell every existing peer about the newcomer AND tell the newcomer
    // about every existing peer. Mirrors SceneMultiplayer::_admit_peer
    // (modules/multiplayer/scene_multiplayer.cpp:368-395).
    const newJoinPacket = addPeerPacket(peerId);
    for (const peer of this.ctx.getWebSockets()) {
      if (peer === server) continue;
      const existing = peer.deserializeAttachment() as SocketMeta | null;
      if (!existing) continue;
      try {
        // Tell the existing peer about the newcomer.
        peer.send(newJoinPacket);
        // Tell the newcomer about the existing peer.
        server.send(addPeerPacket(existing.peerId));
      } catch {
        // Peer's socket is in a bad state — webSocketClose will clean up.
      }
    }

    // If this room has a persisted world, hand it to the new peer in the join
    // burst — even if the room was empty (everyone had left) and the DO was
    // hibernated/evicted in between. Frame: [WORLD_LOAD][...blob]. The store
    // reassembles a chunked (>1MB) world transparently here.
    const world = this.worldStore.load();
    if (world !== null) {
      const frame = new Uint8Array(1 + world.byteLength);
      frame[0] = WORLD_LOAD;
      frame.set(world, 1);
      try {
        server.send(frame);
      } catch {
        // new socket already gone — webSocketClose handles cleanup
      }
    }

    // Hand the joiner the full current shared-state doc (no-host authoritative
    // model) so a late/reconnecting peer converges to the same state the room
    // already committed — including when the room had been empty and the DO was
    // evicted in between (the state is durable in SQLite). Only sent when state
    // exists: a room that never wrote a key sends NO snapshot frame, exactly
    // like a never-saved world sends no WORLD_LOAD. That keeps the join burst of
    // a pure host-client/relay game byte-identical to before this primitive
    // existed (those games never call state_set), and "no snapshot = empty
    // state" is the joiner's unambiguous contract.
    const snapshot = this.sharedStateStore.snapshot();
    if (snapshot.length > 0) {
      try {
        server.send(encodeStateSnapshot(snapshot));
      } catch {
        // new socket already gone — webSocketClose handles cleanup
      }
    }

    if (isFirstPeer) {
      this.emitEvent({
        event_type: "room_created",
        devUserId,
        gameId,
        roomId,
        bytesIn: 0,
        bytesOut: 0,
        peerCount: 1,
      });
    }
    this.emitEvent({
      event_type: "peer_joined",
      devUserId,
      gameId,
      roomId,
      bytesIn: 0,
      bytesOut: 0,
      peerCount: this.ctx.getWebSockets().length,
      extra: { peerId },
    });

    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  async webSocketMessage(ws: WebSocket, message: string | ArrayBuffer): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (!meta) {
      // No attachment means the socket somehow bypassed fetch(). Close it.
      ws.close(1011, "missing_attachment");
      return;
    }

    // world_save — persist an opaque blob for the room. Frame:
    // [WORLD_SAVE][...blob]. Handled before the per-second byte rate limit so a
    // legitimate multi-MB world save isn't killed by the realtime-traffic cap;
    // its own WORLD_MAX_BYTES ceiling (enforced in the store) bounds abuse.
    if (typeof message !== "string") {
      const v0 = new Uint8Array(message);
      if (v0.length >= 1 && v0[0] === WORLD_SAVE) {
        const blob = v0.slice(1);
        try {
          this.worldStore.save(blob);
        } catch (err) {
          // Fail LOUD — never silently drop a save the game thinks succeeded.
          // An oversized/rejected world closes the socket with a debuggable
          // reason and emits an observable event; the game sees the close, not
          // a phantom success.
          const reason =
            err instanceof WorldTooLargeError ? "world_too_large" : "world_save_failed";
          this.emitEvent({
            event_type: "world_save_rejected",
            devUserId: meta.devUserId,
            gameId: meta.gameId,
            roomId: meta.roomId,
            bytesIn: blob.byteLength,
            bytesOut: 0,
            peerCount: this.ctx.getWebSockets().length,
            extra: {
              peerId: meta.peerId,
              reason,
              size: blob.byteLength,
              error: String((err as Error).message ?? err),
            },
          });
          ws.close(1009, reason); // 1009 = message too big
          return;
        }
        try {
          ws.send(new Uint8Array([WORLD_SAVE_ACK]));
        } catch {
          /* socket gone */
        }
        this.emitEvent({
          event_type: "world_saved",
          devUserId: meta.devUserId,
          gameId: meta.gameId,
          roomId: meta.roomId,
          bytesIn: blob.byteLength,
          bytesOut: 1,
          peerCount: this.ctx.getWebSockets().length,
          extra: { peerId: meta.peerId, size: blob.byteLength },
        });
        return;
      }

      // state_set — a write into the live per-key shared doc (no-host
      // authoritative model). Handled here, BEFORE the realtime byte cap and
      // entirely separate from the Godot relay path, for the same reason as
      // world saves: a legitimate large value mustn't be killed by the
      // realtime cap (its own SHARED_VALUE_MAX_BYTES bounds abuse), AND the DO
      // — not a host — is the single writer-orderer that assigns the rev.
      if (v0.length >= 1 && v0[0] === STATE_SET) {
        this.handleStateSet(ws, meta, v0);
        return;
      }
    }

    const now = Date.now();
    const byteSize =
      typeof message === "string"
        ? new TextEncoder().encode(message).byteLength
        : message.byteLength;

    // Sliding 1-second window. Reset counters when the window has expired.
    if (now - meta.windowStart >= RATE_WINDOW_MS) {
      meta.windowStart = now;
      meta.windowMsgs = 0;
      meta.windowBytes = 0;
    }
    meta.windowMsgs += 1;
    meta.windowBytes += byteSize;
    meta.totalBytesIn += byteSize;

    if (
      meta.windowMsgs > RATE_LIMIT_MSGS_PER_SEC ||
      meta.windowBytes > RATE_LIMIT_BYTES_PER_SEC
    ) {
      this.emitEvent({
        event_type: "rate_limit_hit",
        devUserId: meta.devUserId,
        gameId: meta.gameId,
        roomId: meta.roomId,
        bytesIn: byteSize,
        bytesOut: 0,
        peerCount: this.ctx.getWebSockets().length,
        extra: { peerId: meta.peerId, budget: RATE_LIMIT_BYTES_PER_SEC },
      });
      ws.serializeAttachment(meta);
      ws.close(1008, "rate_limit_exceeded");
      return;
    }

    // Strings are not part of the Godot protocol — anything text on this
    // socket is a bug in the sender. Drop it loudly so it's debuggable.
    if (typeof message === "string") {
      ws.serializeAttachment(meta);
      this.emitEvent({
        event_type: "text_frame_dropped",
        devUserId: meta.devUserId,
        gameId: meta.gameId,
        roomId: meta.roomId,
        bytesIn: byteSize,
        bytesOut: 0,
        peerCount: this.ctx.getWebSockets().length,
        extra: { peerId: meta.peerId },
      });
      return;
    }

    const view = new Uint8Array(message);
    let bytesOutTotal = 0;

    // SYS_COMMAND_RELAY — parse the target peer and route. SceneMultiplayer
    // generates these for every @rpc / SYNC / SPAWN. The Worker rewrites
    // the sender_id in the relay header and forwards the inner payload
    // unchanged.
    if (isRelayPacket(view)) {
      const header = parseRelayHeader(view);
      const out = rewriteRelaySender(view, meta.peerId);

      if (header.targetPeer > 0) {
        // Unicast.
        for (const peer of this.ctx.getWebSockets()) {
          if (peer === ws) continue;
          const m = peer.deserializeAttachment() as SocketMeta | null;
          if (!m || m.peerId !== header.targetPeer) continue;
          try {
            peer.send(out);
            bytesOutTotal += out.byteLength;
            m.totalBytesOut += out.byteLength;
            peer.serializeAttachment(m);
          } catch {
            // Bad socket — its own webSocketClose handles cleanup.
          }
          break;
        }
      } else {
        // Broadcast. target=0 → all-except-sender. target=-N → all-except-sender-and-N.
        const exclude = header.targetPeer === 0 ? null : -header.targetPeer;
        for (const peer of this.ctx.getWebSockets()) {
          if (peer === ws) continue;
          const m = peer.deserializeAttachment() as SocketMeta | null;
          if (!m) continue;
          if (exclude !== null && m.peerId === exclude) continue;
          try {
            peer.send(out);
            bytesOutTotal += out.byteLength;
            m.totalBytesOut += out.byteLength;
            peer.serializeAttachment(m);
          } catch {
            // Bad socket — its own webSocketClose handles cleanup.
          }
        }
      }

      meta.totalBytesOut += 0; // sender's own bytes-out is from receiving replies
      ws.serializeAttachment(meta);

      this.emitEvent({
        event_type: "relay",
        devUserId: meta.devUserId,
        gameId: meta.gameId,
        roomId: meta.roomId,
        bytesIn: byteSize,
        bytesOut: bytesOutTotal,
        peerCount: this.ctx.getWebSockets().length,
      });
      return;
    }

    // SYS_COMMAND_AUTH — pure peer-to-peer handshake. Broadcast to everyone
    // else; the Worker has no opinion on its contents.
    if (isAuthPacket(view)) {
      for (const peer of this.ctx.getWebSockets()) {
        if (peer === ws) continue;
        try {
          peer.send(view);
          bytesOutTotal += view.byteLength;
          const m = peer.deserializeAttachment() as SocketMeta | null;
          if (m) {
            m.totalBytesOut += view.byteLength;
            peer.serializeAttachment(m);
          }
        } catch {
          // Bad socket — its own webSocketClose handles cleanup.
        }
      }

      ws.serializeAttachment(meta);
      this.emitEvent({
        event_type: "auth",
        devUserId: meta.devUserId,
        gameId: meta.gameId,
        roomId: meta.roomId,
        bytesIn: byteSize,
        bytesOut: bytesOutTotal,
        peerCount: this.ctx.getWebSockets().length,
      });
      return;
    }

    // Anything else (raw NETWORK_COMMAND_REMOTE_CALL etc sent directly,
    // without a RELAY wrapper) shouldn't happen with the standard Godot
    // SceneMultiplayer client — but log + drop instead of crashing so we
    // see the problem during dev.
    const cmdLow = view.length > 0 ? view[0] & 0x7 : -1;
    ws.serializeAttachment(meta);
    this.emitEvent({
      event_type: "unknown_packet_dropped",
      devUserId: meta.devUserId,
      gameId: meta.gameId,
      roomId: meta.roomId,
      bytesIn: byteSize,
      bytesOut: 0,
      peerCount: this.ctx.getWebSockets().length,
      extra: {
        peerId: meta.peerId,
        cmd: cmdLow,
        sub: view.length > 1 ? view[1] : -1,
        size: view.byteLength,
      },
    });
  }

  async webSocketClose(
    ws: WebSocket,
    code: number,
    reason: string,
    _wasClean: boolean,
  ): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (meta) {
      // Notify remaining peers so they can update their membership view.
      const leaveFrame = delPeerPacket(meta.peerId);
      let bytesOutTotal = 0;
      for (const peer of this.ctx.getWebSockets()) {
        if (peer === ws) continue;
        try {
          peer.send(leaveFrame);
          bytesOutTotal += leaveFrame.byteLength;
          const m = peer.deserializeAttachment() as SocketMeta | null;
          if (m) {
            m.totalBytesOut += leaveFrame.byteLength;
            peer.serializeAttachment(m);
          }
        } catch {
          // Peer's socket is gone — its own webSocketClose handles cleanup.
        }
      }
      // Emit per-connection totals so the rollup attributes lifetime traffic
      // to this user. bytesIn = sum of bytes this peer sent; bytesOut = sum of
      // bytes this peer received from others (accumulated by the sender's
      // routing loop).
      this.emitEvent({
        event_type: "peer_left",
        devUserId: meta.devUserId,
        gameId: meta.gameId,
        roomId: meta.roomId,
        bytesIn: meta.totalBytesIn,
        bytesOut: meta.totalBytesOut,
        peerCount: Math.max(0, this.ctx.getWebSockets().length - 1),
        extra: { peerId: meta.peerId, code, reason, broadcastBytes: bytesOutTotal },
      });
    }
    // Ensure the socket is fully closed even if the close came from the peer.
    try {
      ws.close(code, reason);
    } catch {
      // Already closed.
    }
    this.maybeEmitRoomClosed();
  }

  async webSocketError(ws: WebSocket, error: unknown): Promise<void> {
    const meta = ws.deserializeAttachment() as SocketMeta | null;
    if (meta) {
      this.emitEvent({
        event_type: "peer_error",
        devUserId: meta.devUserId,
        gameId: meta.gameId,
        roomId: meta.roomId,
        bytesIn: 0,
        bytesOut: 0,
        peerCount: this.ctx.getWebSockets().length,
        extra: {
          peerId: meta.peerId,
          error: String((error as Error)?.message ?? error),
        },
      });
    }
    this.maybeEmitRoomClosed();
  }

  // ---- internals ----

  private nextPeerId(): number {
    // UPDATE...RETURNING is atomic in SQLite; coalesced with no awaits between
    // so the read+write commits as one transaction. Counter is seeded at 1
    // (server's implicit id) so the first real client gets id=2 — matches
    // the >=2 invariant Godot enforces in websocket_multiplayer_peer.cpp.
    const row = this.ctx.storage.sql
      .exec<{ value: number }>(
        "UPDATE room_state SET value = value + 1 WHERE key = 'peer_counter' RETURNING value",
      )
      .one();
    return row.value;
  }

  // Allocate the next shared-state revision. UPDATE...RETURNING is atomic and
  // coalesced (no awaits) so concurrent state_set writes get strictly
  // increasing, never-duplicated revs — this is the room-wide commit order that
  // makes last-writer-wins well-defined.
  private nextRev(): number {
    const row = this.ctx.storage.sql
      .exec<{ value: number }>(
        "UPDATE room_state SET value = value + 1 WHERE key = 'state_rev' RETURNING value",
      )
      .one();
    return row.value;
  }

  // Commit one state_set, then broadcast the committed state_update to EVERY
  // connected peer — including the sender, so it learns the DO-assigned rev and
  // the global commit order (not just its own optimistic value). The DO is the
  // single writer-orderer here; webSocketMessage delivers frames one at a time,
  // so assigning the rev + persisting + broadcasting is already serialized per
  // DO. We do NOT validate game rules — this prevents desync, not cheating.
  private handleStateSet(
    ws: WebSocket,
    meta: SocketMeta,
    frame: Uint8Array,
  ): void {
    let key: string;
    let value: Uint8Array;
    try {
      ({ key, value } = decodeStateSet(frame));
    } catch (err) {
      // Malformed frame — fail LOUD and debuggable, never silently ignore a
      // write the game believes it made. Close with an observable reason.
      this.emitEvent({
        event_type: "state_set_rejected",
        devUserId: meta.devUserId,
        gameId: meta.gameId,
        roomId: meta.roomId,
        bytesIn: frame.byteLength,
        bytesOut: 0,
        peerCount: this.ctx.getWebSockets().length,
        extra: {
          peerId: meta.peerId,
          reason: "malformed_state_set",
          error: String((err as Error).message ?? err),
        },
      });
      ws.close(1008, "malformed_state_set");
      return;
    }

    const rev = this.nextRev();
    try {
      this.sharedStateStore.set(key, value, rev);
    } catch (err) {
      // Oversized/failed persist — same loud-failure contract as world saves.
      const reason =
        err instanceof SharedValueTooLargeError
          ? "state_value_too_large"
          : "state_set_failed";
      this.emitEvent({
        event_type: "state_set_rejected",
        devUserId: meta.devUserId,
        gameId: meta.gameId,
        roomId: meta.roomId,
        bytesIn: frame.byteLength,
        bytesOut: 0,
        peerCount: this.ctx.getWebSockets().length,
        extra: {
          peerId: meta.peerId,
          reason,
          key,
          size: value.byteLength,
          error: String((err as Error).message ?? err),
        },
      });
      ws.close(1009, reason); // 1009 = message too big
      return;
    }

    // Broadcast the committed update to ALL peers, sender included. Last-
    // writer-wins is resolved client-side by `rev`: a peer applies an update
    // only if its rev exceeds the rev it already holds for that key.
    const update = encodeStateUpdate(key, value, rev);
    let bytesOut = 0;
    for (const peer of this.ctx.getWebSockets()) {
      const m =
        peer === ws ? meta : (peer.deserializeAttachment() as SocketMeta | null);
      if (!m) continue;
      try {
        peer.send(update);
        bytesOut += update.byteLength;
        m.totalBytesOut += update.byteLength;
        if (peer !== ws) peer.serializeAttachment(m);
      } catch {
        // Bad socket — its own webSocketClose handles cleanup.
      }
    }
    // Persist the sender's updated counters once (it was mutated in the loop).
    ws.serializeAttachment(meta);

    this.emitEvent({
      event_type: "state_set",
      devUserId: meta.devUserId,
      gameId: meta.gameId,
      roomId: meta.roomId,
      bytesIn: frame.byteLength,
      bytesOut,
      peerCount: this.ctx.getWebSockets().length,
      extra: { peerId: meta.peerId, key, rev, size: value.byteLength },
    });
  }

  private maybeEmitRoomClosed(): void {
    const remaining = this.ctx.getWebSockets().length;
    if (remaining === 0) {
      this.emitEvent({
        event_type: "room_closed",
        devUserId: "",
        gameId: "",
        roomId: this.roomId,
        bytesIn: 0,
        bytesOut: 0,
        peerCount: 0,
      });
    }
  }

  private emitEvent(ev: {
    event_type: string;
    devUserId: string;
    gameId: string;
    roomId: string;
    bytesIn: number;
    bytesOut: number;
    peerCount: number;
    extra?: Record<string, unknown>;
  }): void {
    // Console log doubles as observable signal in `wrangler tail` and in tests.
    console.log(
      JSON.stringify({
        event: ev.event_type,
        devUserId: ev.devUserId,
        gameId: ev.gameId,
        roomId: ev.roomId,
        bytesIn: ev.bytesIn,
        bytesOut: ev.bytesOut,
        peerCount: ev.peerCount,
        ...(ev.extra ?? {}),
      }),
    );

    // Analytics Engine — prod sink the rollup cron reads from. Schema:
    //   blobs[0]: event_type
    //   blobs[1]: devUserId  (the user being billed)
    //   blobs[2]: roomId
    //   blobs[3]: game_id    (which game the traffic belongs to)
    //   doubles[0]: bytesIn
    //   doubles[1]: bytesOut
    //   doubles[2]: peerCount
    //   indexes[0]: devUserId — AE allows ONE index per data point and we
    //     query "SUM(bytes) GROUP BY devUserId" so this is the right choice.
    // The binding is optional — present only when AE is enabled on the
    // account (see wrangler.toml comments). Cast through unknown so tsc
    // compiles whether or not `MULTIPLAYER_EVENTS` is in the Env type.
    const events = (this.env as unknown as { MULTIPLAYER_EVENTS?: AnalyticsEngineDataset })
      .MULTIPLAYER_EVENTS;
    if (events) {
      try {
        events.writeDataPoint({
          blobs: [ev.event_type, ev.devUserId, ev.roomId, ev.gameId],
          doubles: [ev.bytesIn, ev.bytesOut, ev.peerCount],
          indexes: [ev.devUserId],
        });
      } catch (err) {
        console.log(
          JSON.stringify({
            event: "ae_write_error",
            error: String((err as Error).message ?? err),
          }),
        );
      }
    }

    // Mirror to the log-drain pipeline so the existing Cloudflare Worker that
    // tails logs can ingest these events alongside web logs. Fire-and-forget.
    const drainUrl = this.env.LOG_DRAIN_URL;
    if (drainUrl) {
      // ctx.waitUntil keeps the fetch alive after the handler returns without
      // blocking message delivery.
      this.ctx.waitUntil(
        fetch(drainUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            event: ev.event_type,
            devUserId: ev.devUserId,
            gameId: ev.gameId,
            roomId: ev.roomId,
            bytesIn: ev.bytesIn,
            bytesOut: ev.bytesOut,
            peerCount: ev.peerCount,
            ts: Date.now(),
            ...(ev.extra ?? {}),
          }),
        }).catch((err) => {
          console.log(
            JSON.stringify({
              event: "log_drain_post_error",
              error: String((err as Error).message ?? err),
            }),
          );
        }),
      );
    }
  }
}
